apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_40b24d79487a
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              value: jdbc:mysql://mysql:3306/everyide
          resources:
            requests:
              memory: 1Gi
          volumeMounts:
            - mountPath: /everyDataBase
              name: everydatabase
      volumes:  # 이 부분이 template: spec 레벨에 들어가야 합니다.
        - name: everydatabase
          persistentVolumeClaim:
            claimName: everydatabase
      readinessProbe:
        httpGet:
          path: /api/test
          port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
