apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_90228e5aad44
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              value: jdbc:mariadb://mariadb:3306/nalsee
          volumeMounts:
          - name: nalsee
            mountPath: "/src/main/resources/application-kram.yml"
          resources:
            requests:
              memory: 1Gi
      readinessProbe:
        httpGet:
          path: /api/test
          port: 8080
      volumes:
      - nmae: nalsee
        secret:
        secretName: my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
