apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hyejin724/nalsee:latest
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              value: jdbc:mariadb://mariadb:3306/nalsee
            - name : KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kakao-secrets
                  key: KAKAO_CLIENT_ID
            - name : KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kakao-secrets
                  key: KAKAO_CLIENT_SECRET
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: kakao-secrets
                  key: KAKAO_REDIRECT_URI
          resources:
            requests:
              memory: 1Gi
      readinessProbe:
        httpGet:
          path: /api/test
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
