# Deployment를 생성하는 YAML 파일
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-env
  template:
    metadata:
      labels:
        app: my-app-env
    spec:
      containers:
        - name: my-app-container-env
          image: my-app-image:latest
          env:
            - name: MY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret-env
                  key: username
              # Secret의 "username" 필드를 환경 변수 MY_USERNAME으로 설정합니다.
            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret-env
                  key: password
              # Secret의 "password" 필드를 환경 변수 MY_PASSWORD로 설정합니다.
